import fs from 'node:fs'
const h = fs.readFileSync('public/cyan/index.html', 'utf8')
console.log('headers', (h.match(/<header class="rstb-header">/g) || []).length)
console.log('univet-page', (h.match(/id="univet-page"/g) || []).length)
console.log('tdyu-main', (h.match(/tdyu-main/g) || []).length)
const hi = h.indexOf('<header')
const mi = h.indexOf('<main')
console.log('header→main chars', mi - hi)
console.log('header preview', h.slice(hi, hi + 200))
console.log('has sub-menu', h.includes('sub-menu'))
console.log('Sahifalar in header only?', h.slice(hi, mi).includes('Sahifalar'))
