import fs from 'node:fs'
import path from 'node:path'

const root = 'public/cyan'

const fixes = [
  ['Magistratura Dasturlar', 'Magistratura dasturlari'],
  ['Postgraduate Dasturlar', 'Magistratura dasturlari'],
  ['Academic Fakultetlar', 'Akademik fakultetlar'],
  ['Kafedra Umumiy ma’lumot', 'Kafedra haqida'],
  ['Kafedra Umumiy ma\'lumot', 'Kafedra haqida'],
  ['Tadqiqot, and student success.', 'Tadqiqot va talaba muvaffaqiyati.'],
  ['A-Daraja', 'A-Level'],
  ['attestat / A-Daraja / ekvivalent', 'attestat / A-Level / ekvivalent'],
  ['and student success', 'va talaba muvaffaqiyati'],
  ['and Scholarly', 'va ilmiy'],
  ['Undergraduate Dasturlar', 'Bakalavriat dasturlari'],
  ['Graduate Dasturlar', 'Magistratura dasturlari'],
  ['Doctoral Dasturlar', 'Doktorantura dasturlari'],
  ['Online Kurslar', 'Onlayn kurslar'],
  ['Our Tadqiqot', 'Bizning tadqiqotlarimiz'],
  ['Our Missiya', 'Bizning missiyamiz'],
  ['Our Kampus', 'Bizning kampus'],
  ['View Barcha', 'Barchasini ko‘rish'],
  ['Learn Ko‘proq', 'Ko‘proq bilish'],
  ['Get Boshlash', 'Boshlash'],
  ['Apply Now', 'Ariza topshirish'],
  ['Read Batafsil', 'Batafsil'],
  ['Click here', 'Bu yerni bosing'],
  ['Learn more', 'Batafsil'],
  ['Show more', 'Ko‘proq ko‘rsatish'],
  ['Show less', 'Kamroq ko‘rsatish'],
  ['Load more', 'Yana yuklash'],
  ['No comments', 'Izohlar yo‘q'],
  ['Leave a Reply', 'Javob qoldirish'],
  ['Leave a comment', 'Izoh qoldirish'],
  ['Your comment', 'Izohingiz'],
  ['Post Comment', 'Izohni yuborish'],
  ['Related Posts', 'Tegishli maqolalar'],
  ['Recent Posts', 'So‘nggi maqolalar'],
  ['Popular Posts', 'Mashhur maqolalar'],
  ['Search Results', 'Qidiruv natijalari'],
  ['Nothing Found', 'Hech narsa topilmadi'],
  ['Page not found', 'Sahifa topilmadi'],
  ['Back to Home', 'Bosh sahifaga qaytish'],
  ['Back to home', 'Bosh sahifaga qaytish'],
  ['All Categories', 'Barcha turkumlar'],
  ['Select Category', 'Turkumni tanlang'],
  ['No posts found', 'Maqolalar topilmadi'],
  ['Posted on', 'Chop etilgan'],
  ['Posted by', 'Muallif'],
  ['Written by', 'Muallif'],
  ['Share this', 'Ulashish'],
  ['Share on', 'Ulashish'],
  ['Follow on', 'Kuzatish'],
  ['Subscribe', 'Obuna bo‘lish'],
  ['Subscribe Now', 'Hozir obuna bo‘ling'],
  ['Enter your email', 'Emailingizni kiriting'],
  ['Your email', 'Emailingiz'],
  ['First Name', 'Ism'],
  ['Last Name', 'Familiya'],
  ['Full Name', 'To‘liq ism'],
  ['Subject', 'Mavzu'],
  ['Send Message', 'Xabar yuborish'],
  ['Send message', 'Xabar yuborish'],
  ['Thank you', 'Rahmat'],
  ['Successfully', 'Muvaffaqiyatli'],
  ['Error', 'Xato'],
  ['Required', 'Majburiy'],
  ['Optional', 'Ixtiyoriy'],
  ['Available', 'Mavjud'],
  ['Unavailable', 'Mavjud emas'],
  ['Coming Soon', 'Tez orada'],
  ['Featured', 'Tanlangan'],
  ['Popular', 'Mashhur'],
  ['Latest', 'So‘nggi'],
  ['Trending', 'Trend'],
  ['New', 'Yangi'],
  ['Hot', 'Dolzarb'],
  ['Free', 'Bepul'],
  ['Paid', 'Pullik'],
  ['Price', 'Narx'],
  ['Total', 'Jami'],
  ['Subtotal', 'Oraliq jami'],
  ['Discount', 'Chegirma'],
  ['Quantity', 'Miqdor'],
  ['Add to Cart', 'Savatga qo‘shish'],
  ['Buy Now', 'Hozir sotib olish'],
  ['Checkout', 'To‘lov'],
  ['Continue', 'Davom etish'],
  ['Finish', 'Tugatish'],
  ['Complete', 'Yakunlash'],
  ['Start', 'Boshlash'],
  ['Stop', 'To‘xtatish'],
  ['Pause', 'Pauza'],
  ['Play', 'Ijro'],
  ['Watch Video', 'Videoni ko‘rish'],
  ['Watch Now', 'Hozir ko‘rish'],
  ['Download PDF', 'PDF yuklab olish'],
  ['Download Brochure', 'Buklet yuklab olish'],
  ['View Profile', 'Profilni ko‘rish'],
  ['View Details', 'Tafsilotlarni ko‘rish'],
  ['See All', 'Barchasini ko‘rish'],
  ['See More', 'Yana ko‘rish'],
  ['Explore', 'O‘rganish'],
  ['Discover', 'Kashf etish'],
  ['Join Us', 'Bizga qo‘shiling'],
  ['Join Now', 'Hozir qo‘shiling'],
  ['Become a Member', 'A’zo bo‘lish'],
  ['Our Team', 'Bizning jamoa'],
  ["Meet Our Team", 'Jamoamiz bilan tanishing'],
  ['Our Story', 'Bizning hikoya'],
  ['Our History', 'Bizning tarix'],
  ['Who We Are', 'Biz kimmiz'],
  ['What We Do', 'Nima qilamiz'],
  ['How It Works', 'Qanday ishlaydi'],
  ['Get Help', 'Yordam olish'],
  ['Help Center', 'Yordam markazi'],
  ['Support Center', 'Qo‘llab-quvvatlash markazi'],
  ['Customer Support', 'Mijozlarni qo‘llab-quvvatlash'],
  ['Live Chat', 'Jonli chat'],
  ['Call Now', 'Hozir qo‘ng‘iroq qiling'],
  ['Book Now', 'Hozir band qiling'],
  ['Book a Visit', 'Tashrifni band qilish'],
  ['Schedule a Visit', 'Tashrifni rejalashtirish'],
  ['Request Info', 'Ma’lumot so‘rash'],
  ['Request Information', 'Ma’lumot so‘rash'],
  ['Talk to Advisor', 'Maslahatchi bilan gaplashish'],
  ['Academic Calendar', 'Akademik taqvim'],
  ['Course Catalog', 'Kurslar katalogi'],
  ['Student Life', 'Talaba hayoti'],
  ['Student Portal', 'Talaba portali'],
  ['Parent Portal', 'Ota-ona portali'],
  ['Career Services', 'Karyera xizmatlari'],
  ['Career Center', 'Karyera markazi'],
  ['Job Placement', 'Ishga joylashish'],
  ['Internship', 'Amaliyot'],
  ['Internships', 'Amaliyotlar'],
  ['Exchange Program', 'Almashinuv dasturi'],
  ['Study Abroad', 'Xorijda o‘qish'],
  ['International Students', 'Xalqaro talabalar'],
  ['Domestic Students', 'Mahalliy talabalar'],
  ['Transfer Students', 'O‘tkazma talabalar'],
  ['New Students', 'Yangi talabalar'],
  ['Current Students', 'Hozirgi talabalar'],
  ['Prospective Students', 'Kelajakdagi talabalar'],
  ['Faculty & Staff', 'Professor-o‘qituvchilar va xodimlar'],
  ['Faculty &amp; Staff', 'Professor-o‘qituvchilar va xodimlar'],
  ['Staff Directory', 'Xodimlar ro‘yxati'],
  ['Office of the', 'Idorasi:'],
  ['Board of Trustees', 'Vasiylik kengashi'],
  ['Board of Directors', 'Direktorlar kengashi'],
  ['Annual Report', 'Yillik hisobot'],
  ['Financial Aid', 'Moliyaviy yordam'],
  ['Student Housing', 'Talabalar turar joyi'],
  ['Dining Services', 'Ovqatlanish xizmati'],
  ['Health Services', 'Sog‘liqni saqlash xizmati'],
  ['Counseling', 'Maslahat'],
  ['Accessibility', 'Qulaylik'],
  ['Diversity', 'Xilma-xillik'],
  ['Inclusion', 'Inkluziya'],
  ['Sustainability', 'Barqarorlik'],
  ['Safety', 'Xavfsizlik'],
  ['Security', 'Xavfsizlik'],
  ['Emergency', 'Favqulodda'],
  ['Important Dates', 'Muhim sanalar'],
  ['Key Dates', 'Asosiy sanalar'],
  ['Deadlines', 'Muddatlar'],
  ['Deadline', 'Muddat'],
  ['Application Deadline', 'Ariza muddati'],
  ['Open Day', 'Ochiq eshiklar kuni'],
  ['Open House', 'Ochiq eshiklar'],
  ['Orientation', 'Orientatsiya'],
  ['Commencement', 'Bitiruv marosimi'],
  ['Graduation', 'Bitiruv'],
  ['Convocation', 'Tantanali yig‘ilish'],
  ['Conference', 'Konferensiya'],
  ['Workshop', 'Seminar'],
  ['Seminar', 'Seminar'],
  ['Webinar', 'Vebinar'],
  ['Symposium', 'Simpozium'],
  ['Exhibition', 'Ko‘rgazma'],
  ['Competition', 'Musobaqa'],
  ['Contest', 'Tanlov'],
  ['Championship', 'Chempionat'],
  ['Tournament', 'Turnir'],
  ['Festival', 'Festival'],
  ['Celebration', 'Bayram'],
  ['Ceremony', 'Marosim'],
  ['Meeting', 'Yig‘ilish'],
  ['Announcement', 'E’lon'],
  ['Announcements', 'E’lonlar'],
  ['Press Release', 'Matbuot xabari'],
  ['Media Center', 'Media markaz'],
  ['Newsroom', 'Yangiliklar xonasi'],
  ['In the News', 'Matbuotda'],
  ['Featured News', 'Asosiy yangiliklar'],
  ['Latest News', 'So‘nggi yangiliklar'],
  ['Campus News', 'Kampus yangiliklari'],
  ['University News', 'Universitet yangiliklari'],
]

function walk(dir, files = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const f = path.join(dir, e.name)
    if (e.isDirectory()) walk(f, files)
    else if (/\.html?$/i.test(e.name)) files.push(f)
  }
  return files
}

function withProtected(html, fn) {
  const blocks = []
  const masked = html.replace(/<(script|style)(\b[^>]*)>[\s\S]*?<\/\1>/gi, (m) => {
    blocks.push(m)
    return `@@B${blocks.length - 1}@@`
  })
  let out = fn(masked)
  return out.replace(/@@B(\d+)@@/g, (_, i) => blocks[Number(i)])
}

let n = 0
for (const file of walk(root)) {
  const raw = fs.readFileSync(file, 'utf8')
  const next = withProtected(raw, (t) => {
    let o = t
    for (const [a, b] of fixes) {
      if (o.includes(a)) o = o.split(a).join(b)
    }
    return o
  })
  if (next !== raw) {
    fs.writeFileSync(file, next)
    n++
  }
}
console.log(`Cleanup: ${n} files`)
