/** Inglizcha → o‘zbekcha (lotin). Uzunroq iboralar birinchi qo‘llanadi. */
export const uzDict = [
  // Long phrases first
  ["We searched the space, but we couldn't find the page you're looking for.", "Sahifani qidirib ko‘rdik, lekin siz izlagan sahifa topilmadi."],
  ["Completed secondary education (HSC/A-Level/Equivalent).", "O‘rta maxsus ta’lim tugallangan (attestat / A-Level / ekvivalent)."],
  ["Minimum GPA/grade requirements as set by the university.", "Universitet belgilagan minimal GPA / baho talablari."],
  ["For graduate programs: a recognized bachelor’s degree with required CGPA.", "Magistratura uchun: tan olingan bakalavr diplomi va zarur CGPA."],
  ["Our university is committed to advancing knowledge through innovative.", "Universitetimiz innovatsiyalar orqali bilimni rivojlantirishga sodiq."],
  ["Enroll now to begin your transformative academic journey with us.", "Biz bilan o‘zgaruvchan akademik yo‘lingizni boshlash uchun hozir ro‘yxatdan o‘ting."],
  ["Join a diverse campus community through a simple application and visa guidance.", "Oddiy ariza va viza yo‘riqnomasi orqali xilma-xil kampus jamiyatiga qo‘shiling."],
  ["Advance your legal expertise with an internationally recognized.", "Xalqaro e’tirof etilgan dastur bilan huquqiy bilimingizni chuqurlashtiring."],
  ["Explore the world of coding data and innovation with a degree.", "Dasturlash, ma’lumotlar va innovatsiya olamini o‘rganing."],
  ["Explore advanced knowledge and discovery through guide research.", "Ilmiy izlanishlar orqali chuqur bilim va kashfiyotlarni o‘rganing."],
  ["B.Sc. in Mechanical Engineering provides strong theoretical", "Mexanika muhandisligi bakalavriati mustahkam nazariy asos beradi"],
  ["Advancing Knowledge Through Student Research", "Talaba tadqiqotlari orqali bilimni rivojlantirish"],
  ["Univet Scholars Making Remarkable Research", "TDYU olimlari ajoyib tadqiqotlar olib bormoqda"],
  ["Alumni Success Stories From Campus to Global Impact", "Kampusdan global ta’sirgacha: bitiruvchilar muvaffaqiyati"],
  ["The Future of Science and Technology on Campus", "Kampusda fan va texnologiyaning kelajagi"],
  ["Advancing Knowledge, Innovation, and Scholarly Leadership", "Bilim, innovatsiya va ilmiy yetakchilikni rivojlantirish"],
  ["Students participating in this summit will learn to:", "Ushbu sammit ishtirokchilari quyidagilarni o‘rganadi:"],
  ["Understand the principles of academic excellence and scholarly rigor", "Akademik mukammallik va ilmiy qat’iylik tamoyillarini tushunish"],
  ["Apply critical and analytical thinking to academic and real-world problems", "Akademik va hayotiy muammolarga tanqidiy va tahliliy yondashuv"],
  ["Identify opportunities for undergraduate and graduate research engagement", "Bakalavr va magistratura tadqiqot imkoniyatlarini aniqlash"],
  ["Participate confidently in intellectual debates and knowledge exchange", "Intellektual bahslar va bilim almashinuvida ishonchli ishtirok"],
  ["Prepare for future challenges in higher education and research careers", "Oliy ta’lim va tadqiqot karyerasidagi kelajak sinovlariga tayyorgarlik"],
  ["Full-Time Tuition (Per semesters): $300", "Kunduzgi o‘qish to‘lovi (har semestr): $300"],
  ["Ph.D. in Mathematics, University of Cambridge", "Matematika fanlari doktori, Kembrij universiteti"],
  ["M.SC. in Mathematics. University of California", "Matematika magistri, Kaliforniya universiteti"],
  ["B.Sc. in mathematics, University of Helsinki", "Matematika bakalavri, Helsinki universiteti"],
  ["University Sport & Fitness", "Universitet sporti va fitnes"],
  ["University Sport &amp; Fitness", "Universitet sporti va fitnes"],
  ["Empowering Minds Inspiring", "Ongni kuchaytirish, ilhomlantirish"],
  ["Introduction to the Faculty", "Fakultetga kirish"],
  ["Lead of Faculty", "Fakultet rahbari"],
  ["Expert educators", "Malakali o‘qituvchilar"],
  ["Read Our Latest News", "So‘nggi yangiliklarimizni o‘qing"],
  ["Do Your Need Help?", "Yordam kerakmi?"],
  ["Journey of Our Graduates", "Bitiruvchilarimiz yo‘li"],
  ["Students Feedback", "Talabalar fikr-mulohazasi"],
  ["Academics & Programs", "Akademiya va dasturlar"],
  ["Academics &amp; Programs", "Akademiya va dasturlar"],
  ["Programs & Study", "Dasturlar va ta’lim"],
  ["Programs &amp; Study", "Dasturlar va ta’lim"],
  ["Related Programs", "Tegishli dasturlar"],
  ["Department Overview", "Kafedra haqida"],
  ["Academic Qualifications", "Akademik malaka"],
  ["Research Interests", "Ilmiy qiziqishlar"],
  ["Professional Experience", "Kasbiy tajriba"],
  ["Algebraic Geometry", "Algebraik geometriya"],
  ["Number Theory", "Sonlar nazariyasi"],
  ["Discreate Geometry", "Diskret geometriya"],
  ["Event Speakers", "Tadbir ma’ruzachilari"],
  ["Find the Venue", "Manzilni topish"],
  ["Associate Professor,", "Dotsent,"],
  ["Graduate Programs", "Magistratura dasturlari"],
  ["Campus Events", "Kampus tadbirlari"],
  ["Useful Links", "Foydali havolalar"],
  ["Alumni Network", "Bitiruvchilar tarmog‘i"],
  ["Our Campus", "Bizning kampus"],
  ["Quick Contact:", "Tezkor aloqa:"],
  ["Follow Us:", "Bizni kuzating:"],
  ["Follow us", "Bizni kuzating"],
  ["I agree to the", "Men roziman:"],
  ["About Univet", "TDYU haqida"],
  ["Regular Univet Students", "TDYU talabalari"],
  ["Faculty Members One", "Professor-o‘qituvchilar 1"],
  ["Faculty Members Two", "Professor-o‘qituvchilar 2"],
  ["Faculty Members 01", "Professor-o‘qituvchilar 01"],
  ["Faculty Members 02", "Professor-o‘qituvchilar 02"],
  ["Faculty Members", "Professor-o‘qituvchilar"],
  ["Research Details", "Tadqiqot tafsilotlari"],
  ["Events Details", "Tadbir tafsilotlari"],
  ["Event Details", "Tadbir tafsilotlari"],
  ["Alumni Details", "Bitiruvchi tafsilotlari"],
  ["Member Details", "A’zo tafsilotlari"],
  ["Faculty Details", "Fakultet tafsilotlari"],
  ["Blog Details", "Maqola tafsilotlari"],
  ["Blog Grid 3 Column", "Yangiliklar paneli (3 ustun)"],
  ["Blog Grid Sidebar", "Yangiliklar (yon panel)"],
  ["Blog List Sidebar", "Yangiliklar ro‘yxati"],
  ["Blog Standard", "Yangiliklar (standart)"],
  ["Blog grid", "Yangiliklar paneli"],
  ["M.Ed. in Educational Leadership", "Ta’lim boshqaruvi magistraturasi (M.Ed.)"],
  ["B.Ed. in Educational Leadership", "Ta’lim boshqaruvi bakalavriati (B.Ed.)"],
  ["M.Sc. in Software Engineering", "Dasturiy injiniring magistraturasi"],
  ["B.Sc. in Software Engineering", "Dasturiy injiniring bakalavriati"],
  ["Master of Laws (LLM)", "Huquq magistraturasi (LLM)"],
  ["B.Sc. in CSE", "Kompyuter fanlari bakalavriati"],
  ["M.Sc. in CSE", "Kompyuter fanlari magistraturasi"],
  ["Admission Requirements", "Qabul talablari"],
  ["Cost & Financial Aid", "Narx va moliyaviy yordam"],
  ["Cost &amp; Financial Aid", "Narx va moliyaviy yordam"],
  ["Mission & Value", "Missiya va qiymatlar"],
  ["Mission &amp; Value", "Missiya va qiymatlar"],
  ["Tuition & Fee", "O‘qish to‘lovi"],
  ["Tuition &amp; Fee", "O‘qish to‘lovi"],
  ["How to Apply", "Qanday ariza topshirish"],
  ["All Programs", "Barcha dasturlar"],
  ["All Events", "Barcha tadbirlar"],
  ["Faculty Areas", "Fakultet yo‘nalishlari"],
  ["Vice-Chancellor", "Rektor"],
  ["Campus Map", "Kampus xaritasi"],
  ["Senior Lecturer", "Katta o‘qituvchi"],
  ["Web Developer", "Veb-dasturchi"],
  ["Founder & CEO", "Asoschi va rahbar"],
  ["Founder &amp; CEO", "Asoschi va rahbar"],
  ["Guest Speaker", "Mehmon ma’ruzachi"],
  ["Read More", "Batafsil"],
  ["Social Link", "Ijtimoiy tarmoqlar"],
  ["Ta-134/A, NY 11110, USA", "Saylgoh ko‘chasi 35, Yunusobod, Toshkent 100047"],
  ["Ta-134/A,  NY 11110, USA", "Saylgoh ko‘chasi 35, Yunusobod, Toshkent 100047"],
  ["info@univet.dom", "info@tdyu-endowment.uz"],
  ["info@univet.edu", "info@tdyu-endowment.uz"],

  // Single / short UI
  ["Alumni", "Bitiruvchilar"],
  ["Academics", "Akademiya"],
  ["Scholarships", "Stipendiyalar"],
  ["Libraries", "Kutubxonalar"],
  ["Univet Library", "TDYU kutubxonasi"],
  ["Gallery", "Galereya"],
  ["Programs", "Dasturlar"],
  ["Faculty", "Fakultet"],
  ["Faculties", "Fakultetlar"],
  ["Departments", "Kafedralar"],
  ["Department", "Kafedra"],
  ["Administration", "Ma’muriyat"],
  ["History", "Tarix"],
  ["Newsletter", "Axborotnoma"],
  ["Archives:", "Arxiv:"],
  ["Requirements", "Talablar"],
  ["Curriculum", "O‘quv dasturi"],
  ["Teaching", "O‘qitish"],
  ["Educations", "Ta’lim"],
  ["Education", "Ta’lim"],
  ["Researches", "Tadqiqotlar"],
  ["Research", "Tadqiqot"],
  ["Professor", "Professor"],
  ["Lecturer", "O‘qituvchi"],
  ["Director", "Direktor"],
  ["Manager", "Menejer"],
  ["Others", "Boshqalar"],
  ["Events", "Tadbirlar"],
  ["Event", "Tadbir"],
  ["Faq", "Savol-javob"],
  ["FAQ", "Savol-javob"],
  ["Email:", "Elektron pochta:"],
  ["Phone:", "Telefon:"],
  ["Contact", "Aloqa"],
  ["Submit", "Yuborish"],
  ["Search", "Qidirish"],
  ["Home", "Bosh sahifa"],
  ["About Us", "Biz haqimizda"],
  ["About us", "Biz haqimizda"],
  ["About", "Haqida"],
  ["Campus Life", "Kampus hayoti"],
  ["Campus", "Kampus"],
  ["Admissions", "Qabul"],
  ["Admission", "Qabul"],
  ["Apply Now", "Ariza topshirish"],
  ["Apply", "Ariza"],
  ["Pages", "Sahifalar"],
  ["Blog", "Yangiliklar"],
  ["News", "Yangiliklar"],
  ["Students", "Talabalar"],
  ["Student", "Talaba"],
  ["Teachers", "O‘qituvchilar"],
  ["Teacher", "O‘qituvchi"],
  ["Courses", "Kurslar"],
  ["Course", "Kurs"],
  ["Category", "Turkumi"],
  ["Categories", "Turkumlar"],
  ["Tags", "Teglar"],
  ["Tag", "Teg"],
  ["Comments", "Izohlar"],
  ["Comment", "Izoh"],
  ["Share", "Ulashish"],
  ["Download", "Yuklab olish"],
  ["View All", "Barchasini ko‘rish"],
  ["Learn More", "Ko‘proq bilish"],
  ["Get Started", "Boshlash"],
  ["Sign Up", "Ro‘yxatdan o‘tish"],
  ["Sign In", "Kirish"],
  ["Login", "Kirish"],
  ["Register", "Ro‘yxatdan o‘tish"],
  ["Name", "Ism"],
  ["Message", "Xabar"],
  ["Address", "Manzil"],
  ["Location", "Joylashuv"],
  ["Date", "Sana"],
  ["Time", "Vaqt"],
  ["Duration", "Davomiylik"],
  ["Level", "Daraja"],
  ["Undergraduate", "Bakalavriat"],
  ["Graduate", "Magistratura"],
  ["Doctorate", "Doktorantura"],
  ["International", "Xalqaro"],
  ["National", "Milliy"],
  ["Online", "Onlayn"],
  ["Offline", "Oflayn"],
  ["Full-Time", "Kunduzgi"],
  ["Part-Time", "Sirtqi"],
  ["Semester", "Semestr"],
  ["Year", "Yil"],
  ["Years", "Yillar"],
  ["Credits", "Kreditlar"],
  ["Credit", "Kredit"],
  ["Fee", "To‘lov"],
  ["Fees", "To‘lovlar"],
  ["Tuition", "O‘qish to‘lovi"],
  ["Scholarship", "Stipendiya"],
  ["Grant", "Grant"],
  ["Grants", "Grantlar"],
  ["Award", "Mukofot"],
  ["Awards", "Mukofotlar"],
  ["Achievement", "Yutuq"],
  ["Achievements", "Yutuqlar"],
  ["Success", "Muvaffaqiyat"],
  ["Innovation", "Innovatsiya"],
  ["Leadership", "Yetakchilik"],
  ["Community", "Hamjamiyat"],
  ["Partnership", "Hamkorlik"],
  ["Partners", "Hamkorlar"],
  ["Partner", "Hamkor"],
  ["Support", "Qo‘llab-quvvatlash"],
  ["Donate", "Xayriya"],
  ["Donation", "Xayriya"],
  ["Volunteer", "Ko‘ngilli"],
  ["Privacy Policy", "Maxfiylik siyosati"],
  ["Terms of Service", "Foydalanish shartlari"],
  ["Terms & Conditions", "Foydalanish shartlari"],
  ["Terms &amp; Conditions", "Foydalanish shartlari"],
  ["All Rights Reserved", "Barcha huquqlar himoyalangan"],
  ["Copyright", "Mualliflik huquqi"],
  ["Loading", "Yuklanmoqda"],
  ["Previous", "Oldingi"],
  ["Next", "Keyingi"],
  ["Back", "Orqaga"],
  ["Close", "Yopish"],
  ["Open", "Ochish"],
  ["More", "Ko‘proq"],
  ["Less", "Kamroq"],
  ["Details", "Tafsilotlar"],
  ["Overview", "Umumiy ma’lumot"],
  ["Description", "Tavsif"],
  ["Summary", "Xulosa"],
  ["Results", "Natijalar"],
  ["Result", "Natija"],
  ["Filter", "Filtr"],
  ["Sort by", "Saralash"],
  ["Show", "Ko‘rsatish"],
  ["Hide", "Yashirish"],
  ["Yes", "Ha"],
  ["No", "Yo‘q"],
  ["OK", "OK"],
  ["Cancel", "Bekor qilish"],
  ["Save", "Saqlash"],
  ["Edit", "Tahrirlash"],
  ["Delete", "O‘chirish"],
  ["Update", "Yangilash"],
  ["Send", "Yuborish"],
  ["Call Us", "Qo‘ng‘iroq qiling"],
  ["Email Us", "Email yozing"],
  ["Visit Us", "Bizga tashrif buyuring"],
  ["Our Mission", "Bizning missiyamiz"],
  ["Our Vision", "Bizning vizyonimiz"],
  ["Our Values", "Bizning qiymatlarimiz"],
  ["Why Choose Us", "Nima uchun biz"],
  ["What We Offer", "Nima taklif qilamiz"],
  ["Get In Touch", "Bog‘laning"],
  ["Get in Touch", "Bog‘laning"],
  ["Find Us", "Bizni toping"],
  ["Office Hours", "Ish vaqti"],
  ["Working Hours", "Ish vaqti"],
  ["Monday", "Dushanba"],
  ["Tuesday", "Seshanba"],
  ["Wednesday", "Chorshanba"],
  ["Thursday", "Payshanba"],
  ["Friday", "Juma"],
  ["Saturday", "Shanba"],
  ["Sunday", "Yakshanba"],
  ["January", "Yanvar"],
  ["February", "Fevral"],
  ["March", "Mart"],
  ["April", "Aprel"],
  ["May", "May"],
  ["June", "Iyun"],
  ["July", "Iyul"],
  ["August", "Avgust"],
  ["September", "Sentabr"],
  ["October", "Oktabr"],
  ["November", "Noyabr"],
  ["December", "Dekabr"],
  ["Univet", "TDYU"],
  ["University", "Universitet"],
]

// Title attribute / document titles
export const titleFixes = [
  [/&#8211; TDYU Endowment Fund/g, " – TDYU Endowment Fund"],
  [/&#8211; Cyan University/g, " – TDYU Endowment Fund"],
]
